import "./globals.css";
import Navbar from './navbar/page';
import Footer from './footer/page';

export const metadata = {
  title: "Service Apartments Medanta Medicity Hospital Gurgaon Hotels",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
